using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LearningApplicationTesting
{
    class Recipe
    {
        string[] recipe = new string[9];
        private Recipe()
        {
            string slot1 = "1";
            string slot2 = "1";
            string slot3 = "1";
            string slot4 = "1";
            string slot5 = "1";
            string slot6 = "1";
            string slot7 = "1";
            string slot8 = "1";
            string slot9 = "1";

            recipe[0] = slot1;
            recipe[1] = slot2;
            recipe[2] = slot3;
            recipe[3] = slot4;
            recipe[4] = slot5;
            recipe[5] = slot6;
            recipe[6] = slot7;
            recipe[7] = slot8;
            recipe[8] = slot9;
        }
   
    }
}
